app/Http/routes.php
<?php

Route::get('auth', ['as' => 'login', 'uses' => 'Admin\AuthController@getAuth']);
Route::post('auth', ['as' => 'login', 'uses' => 'Admin\AuthController@postAuth']);
Route::get('logout', ['as' => 'logout', 'uses' => 'Admin\AuthController@getLogout']);

Route::get('/', ['as' => 'app', 'uses' => 'AppController@getApp']);
Route::get('/iframe', [ 'uses' => 'AppController@getIframe']);

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:superadmin|admin']], function () {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'Admin\DashboardController@getDashboard']);
    Route::group(['prefix' => 'users'], function () {
        Route::get('/', ['as' => 'users', 'uses' => 'Admin\UserController@getUsers']);
        Route::get('/create', ['as' => 'create-user', 'uses' => 'Admin\UserController@getCreateUser']);
        Route::post('/create', ['as' => 'create-user', 'uses' => 'Admin\UserController@postCreateUser']);
        Route::get('/view/{user}', ['as' => 'user', 'uses' => 'Admin\UserController@getUser']);
        Route::post('/view/{user}', ['as' => 'update-user', 'uses' => 'Admin\UserController@postUser']);
        Route::get('/delete/{user}', ['as' => 'delete-user', 'uses' => 'Admin\UserController@deleteUser']);
        Route::get('/importcsv/', ['as' => 'import-users-csv', 'uses' => 'Admin\UserController@importUsersCsv']);
        Route::get('/importusersdocs/', ['as' => 'import-users-docs', 'uses' => 'Admin\UserController@importUsersDocs']);
        Route::get('/importteamsdocs/', ['as' => 'import-users-docs', 'uses' => 'Admin\UserController@importTeamsDocs']);
        Route::get('/importteamplayers/', ['as' => 'import-team-users', 'uses' => 'Admin\UserController@importTeamUsers']);


    });

    Route::group(['prefix' => 'teams'], function () {
        Route::get('/', ['as' => 'teams', 'uses' => 'Admin\TeamController@getTeams']);
        Route::get('/create', ['as' => 'create-team', 'uses' => 'Admin\TeamController@getCreateTeam']);
        Route::post('/create', ['as' => 'create-team', 'uses' => 'Admin\TeamController@postCreateTeam']);
        Route::get('/view/{team}', ['as' => 'team', 'uses' => 'Admin\TeamController@getTeam']);
        Route::post('/view/{team}', ['as' => 'update-team', 'uses' => 'Admin\TeamController@postTeam']);
        Route::get('/delete/{team}', ['as' => 'delete-team', 'uses' => 'Admin\TeamController@deleteTeam']);
        Route::get('/changestatus/{team}/{status}', ['as' => 'change-status-team', 'uses' => 'Admin\TeamController@changeStatus']);
        Route::get('/changeregisterstatus/{team}/{status}', ['as' => 'change-status-team', 'uses' => 'Admin\TeamController@changeRegisterStatus']);

    });
    Route::group(['prefix' => 'scheludes'], function () {
        Route::get('/', ['as' => 'scheludes', 'uses' => 'Admin\ScheludeController@index']);
        Route::get('/create', ['as' => 'create-schelude', 'uses' => 'Admin\ScheludeController@getCreate']);
        Route::post('/create', ['as' => 'create-schelude', 'uses' => 'Admin\ScheludeController@postCreate']);
        Route::get('/view/{id}', ['as' => 'schelude', 'uses' => 'Admin\ScheludeController@getSchelude']);
        Route::post('/view/{id}', ['as' => 'update-schelude', 'uses' => 'Admin\ScheludeController@getSchelude']);
        Route::get('/delete/{id}', ['as' => 'delete-schelude', 'uses' => 'Admin\ScheludeController@deleteSchelude']);
        Route::get('/import', ['as' => 'import-schelude', 'uses' => 'Admin\ScheludeController@importSchelude']);

    });
    Route::group(['prefix' => 'photo'], function () {
        Route::post('/upload/{type}/{team}', ['as' => 'photo-team-upload', 'uses' => 'Admin\PhotoController@uploadPhoto'])
            ->where('type', 'team');
        Route::post('/upload/{type}/{user}', ['as' => 'photo-user-upload', 'uses' => 'Admin\PhotoController@uploadPhoto'])
            ->where('type', '(team|user)');
        Route::post('/delete/{photo}', ['as' => 'admin-photo-delete', 'uses' => 'Admin\PhotoController@deletePhoto']);

    });
});

Route::group(['prefix' => 'api/v1', 'middleware' => ['api']], function () {
    Route::group(['prefix' => 'auth'], function () {
        Route::get('/', 'App\AuthController@getUser');
        Route::get('/logout', 'App\AuthController@getLogout');
        Route::post('/login', 'App\AuthController@postLogin');
        Route::post('/reset', 'App\AuthController@postReset');
    });
    Route::get('/teams', 'App\TeamController@getTeams');
    Route::get('/teams/{id}', 'App\TeamController@getTeam');
    Route::get('/teams/search/{name}', ['as' => 'search-teams', 'uses' => 'App\TeamController@getSearch']);


    Route::post('/teams', 'App\TeamController@postTeam');
    Route::post('/teams/{team}/players', 'App\UserController@postTeamPlayer');
    Route::group(['middleware' => ['auth']], function () {
        Route::post('/teams/{team}/players/{user}', 'App\UserController@putTeamPlayer');
        Route::group(['middleware' => ['role:superadmin|admin|captain']], function () {
            Route::delete('/teams/{team}/players/{user}', 'App\UserController@deleteTeamPlayer');
            Route::post('/teams/{team}/players/{user}/accept', 'App\UserController@postAcceptTeamPlayer');
            Route::post('/teams/{team}/players/{user}/decline', 'App\UserController@postDeclineTeamPlayer');
        });
    });
});
Route::group(['prefix' => 'remove'], function () {
    Route::get('user', ['as' => 'remove-user', 'uses' => 'App\UserController@getRemove']);
    Route::get('team', ['as' => 'remove-team', 'uses' => 'App\TeamController@getRemove']);
});

app/Models/User.php
<?php

namespace App\Models;

use Bican\Roles\Traits\HasRoleAndPermission;
use Bican\Roles\Contracts\HasRoleAndPermission as HasRoleAndPermissionContract;
use Bican\Roles\Models\Role;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Hash;
use Mail;

class User extends Authenticatable implements HasRoleAndPermissionContract
{
    use HasRoleAndPermission;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'surname', 'phone',  'email', 'password', 'birthday', 'about'
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'created_at', 'updated_at',
    ];

    protected $appends = ['in_team', 'team'];

    private function teams()
    {
        return $this->belongsToMany('App\Models\Team', 'team_players');
    }

    public function photo()
    {
        return $this->morphOne('App\Models\Photo', 'owner')->where('type', '=', 'photo');
    }
    public function getInTeamAttribute()
    {
        return $this->is('player') || $this->is('captain');
    }
    public function getTeamAttribute()
    {
        return $this->teams()->first();
    }
    public function teamAsCaptain()
    {
        return $this->belongsTo('App\Models\Team', 'id', 'captain_id');
    }

    public function getNameAttribute()
    {
        return $this->first_name.' '.$this->last_name;
    }
    public function getSplitBirthdayAttribute()
    {
        return explode('-', $this->birthday);
    }
    public static function createNew($data)
    {
        $date = array_get($data, 'year') . '-' . array_get($data, 'month') . '-' . array_get($data, 'day');
        $user = self::create(array_merge($data, ['birthday' => $date]));
        $user->syncRoles(array_get($data, 'roles', []));

        return $user;
    }

    public function syncRoles($roles)
    {
        $this->roles = null;

        return empty($roles) ? $this->detachAllRoles() : $this->roles()->sync($roles);
    }
    public function gradeCaptain()
    {
        $captainRole = Role::where('slug', 'captain')->first();
        $this->attachRole($captainRole);
    }
    public function degradeCaptain()
    {
        $captainRole = Role::where('slug', 'captain')->first();
        $this->detachRole($captainRole);
    }

    public function gradePlayer()
    {
        $playerRole = Role::where('slug', 'player')->first();
        $this->attachRole($playerRole);
    }
    public function degradePlayer()
    {
        $playerRole = Role::where('slug', 'player')->first();
        $this->detachRole($playerRole);
    }

    public function onSaving()
    {
        $this->phone = str_replace(' ', '', $this->phone);
    }
    public function onCreating()
    {
        $this->password = Hash::make($this->password);
        $this->link = str_random(32);
    }
    public function onUpdating()
    {
    }
    public function onDeleting()
    {
        $this->photo()->delete();
    }
    public function getDeclineLink() {
        return env('REMOVE_INST_URL') . '/remove/user?link=' . $this->link;
    }
    // (Максим) (Актуальные письма = п.5 Сделал)
    public function acceptPlayerMail($team)
    {
        $this->sendMail('emails.player.accept', [
            'link' => $team->getTeamLink(),
            'team' => $team,
            'subject' => 'Вітаємо, Ви в команді! Футбольний турнір NIVEA MEN 2016.',
        ]);
    }
    // (Максим) (Актуальные письма = п.6 Сделал)
    public function declinePlayerMail($team)
    {
        $this->sendMail('emails.player.decline', [
            'link' => $team->getTeamLink(),
            'subject' => 'Ваш запит на участь в команді відхилено. Футбольний турнір NIVEA MEN 2016.',
        ]);
    }
    // (Максим) (Актуальные письма = п.2 Сделал)
    public function welcomeCaptainFrontMail($team, $password = null)
    {
        $this->sendMail('emails.team.new', [
            'password'=>$password,
            'user' => $this,
            'link' => $team->getTeamLink(),
            'linkApp' => $team->getAppTeamLink(),
            'linkDecline' => $team->getDeclineLink(),
            'subject' => 'Заявочний лист Вашої команди зареєстровано. Футбольний турнір NIVEA MEN 2016.',
        ]);
    }
    // (Максим) (Актуальные письма = п.1 Сделал)
    public function welcomeCaptainBackMail($team)
    {
        $this->sendMail('emails.team.new_back', [
            'user' => $this,
            'link' => $team->getTeamLink(),
            'linkApp' => $team->getAppTeamLink(),
            'linkDecline' => $team->getDeclineLink(),
            'subject' => 'Ваша Заявка на участь у турнірі NIVEA MEN 2016',
        ]);
    }

    // (Максим) (Актуальные письма = п.4 Сделал)
    public function welcomeUserMail($team)
    {
        $this->sendMail('emails.player.welcome', [
            'link' => $team->getTeamLink(),
            'linkDecline' => $this->getDeclineLink(),
            'team' => $team,
            'subject' => 'Ваш запит на участь в команді відправлено. Футбольний турнір NIVEA MEN 2016.',
        ]);
    }
    // (Максим) (Актуальные письма = п.3 Сделал)
    public function captainNewPlayerMail($team, $user)
    {
        $this->sendMail('emails.captain.new_player', [
            'user' => $user,
            'link' => $team->getTeamLink(),
            'subject' => $user->first_name.' '. $user->last_name. ' хоче грати за Вашу команду в турнірі NIVEA MEN 2016',
        ]);
    }
    public function resetPassword()
    {
        $newPassword = str_random(8);
        $this->update(['password' => Hash::make($newPassword)]);
        $this->sendMail('emails.captain.reset', [
            'user' => $this,
            'password' => $newPassword,
            'subject' => 'Восстановление пароля Футбольный турнир NIVEA MEN',

        ]);
    }


    private function sendMail($teamplate, $data)
    {
        Mail::queue($teamplate, $data, function ($message) use($data) {
            $message->from('play-noreply@NIVEA.kiev.ua', 'Nivea men');
            $message->to($this->email, $this->first_name . ' ' . $this->last_name)
                ->subject($data['subject']);
        });
    }
}

resources/views/admin/auth.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>Admin :: Auth</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:300,400' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" type="text/css" href="/css/auth.css">
</head>

<body class="flat-blue login-page">
    <div class="container">
        <div class="login-box">
            <div>
                <div class="login-form row">
                    <div class="col-sm-12">
                        <div class="login-body">
                            <form method="post" action="{{ route('login') }}">
                                <div class="control">
                                    <input type="text" name="email" class="form-control" value="" placeholder="Email"/>
                                </div>
                                <div class="control">
                                    <input type="password" name="password" class="form-control" value="" placeholder="Password"/>
                                </div>
                                <div class="login-button text-center">
                                    <input type="submit" class="btn btn-primary" value="Login">
                                </div>
                                <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @include('blocks.notifier')
    <script type="text/javascript" src="/js/auth.js"></script>
</body>

</html>

resources/views/admin/dashboard.blade.php
@extends('admin.index')

@section('content')
    <div class="side-body padding-top">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <a href="{{ route('users') }}">
                    <div class="card green summary-inline">
                        <div class="card-body">
                            <i class="icon fa fa-user fa-4x"></i>
                            <div class="content">
                                <div class="title">{{ $users->count() }}</div>
                                <div class="sub-title">Users</div>
                            </div>
                            <div class="clear-both"></div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <a href="{{ route('teams') }}">
                    <div class="card green summary-inline">
                        <div class="card-body">
                            <i class="icon fa fa-users fa-4x"></i>
                            <div class="content">
                                <div class="title">{{ $teams->count() }}</div>
                                <div class="sub-title">Teams</div>
                            </div>
                            <div class="clear-both"></div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <a href="{{ route('scheludes') }}">
                            <div class="card green summary-inline">
                                <div class="card-body">
                                    <i class="icon fa fa-users fa-4x"></i>
                                    <div class="content">
                                        <div class="title">{{ $scheludes->count() }}</div>
                                        <div class="sub-title">Scheludes</div>
                                    </div>
                                    <div class="clear-both"></div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>

            </div>
@endsection

resources/views/admin/index.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>Nivea</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="_token" content="{{ csrf_token() }}">
    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:300,400' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" type="text/css" href="http://ext14.niveamen.ua/23/play_root/public/css/admin.css?time={{time()}}">
</head>

<body class="flat-blue">
    <div class="app-container">
        <div class="row content-container">
            <nav class="navbar navbar-default navbar-fixed-top navbar-top">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-expand-toggle">
                            <i class="fa fa-bars icon"></i>
                        </button>
                        <ol class="breadcrumb navbar-breadcrumb">
                            <li class="active">Dashboard</li>
                        </ol>
                        <button type="button" class="navbar-right-expand-toggle pull-right visible-xs">
                            <i class="fa fa-th icon"></i>
                        </button>
                    </div>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown profile">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ Auth::user()->first_name }} {{ Auth::user()->last_name }} <span class="caret"></span></a>
                            <ul class="dropdown-menu animated fadeInDown">
                                <li>
                                    <div class="profile-info">
                                        <h4 class="username">{{ Auth::user()->first_name }} {{ Auth::user()->last_name }}</h4>
                                        <p>{{ Auth::user()->email }}</p>
                                        <div class="btn-group margin-bottom-2x" role="group">
                                            <a href="{{ route('user', [Auth::user()->id]) }}" type="button" class="btn btn-default"><i class="fa fa-user"></i> Profile</a>
                                            <a href="{{ route('logout') }}" class="btn btn-default"><i class="fa fa-sign-out"></i> Logout</a>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
            <div class="side-menu sidebar-inverse">
                <nav class="navbar navbar-default" role="navigation">
                    <div class="side-menu-container">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">
                                <div class="icon fa fa-paper-plane"></div>
                                <div class="title">Nivea</div>
                            </a>
                            <button type="button" class="navbar-expand-toggle pull-right visible-xs">
                                <i class="fa fa-times icon"></i>
                            </button>
                        </div>
                        <ul class="nav navbar-nav">
                            @include('admin.nav')
                        </ul>
                    </div>
                    <!-- /.navbar-collapse -->
                </nav>
            </div>
            <!-- Main Content -->
            <div class="container-fluid">
                @yield('content')
            </div>
        </div>

    <div>
    @include('blocks.notifier')
    <script type="text/javascript" src="http://ext14.niveamen.ua/23/play_root/public/js/admin.js?time={{time()}}"></script>
</body>

</html>

resources/views/admin/nav.blade.php
<li class="{{Request::is('admin') ? 'active' : '' }}">
    <a href="{{ route('dashboard') }}">
        <span class="icon fa fa-tachometer"></span><span class="title">Dashboard</span>
    </a>
</li>
<li class="{{Request::is('admin/users*') ? 'active' : '' }}">
    <a href="{{ route('users') }}">
        <span class="icon fa fa-user"></span><span class="title">Users</span>
    </a>
</li>
<li class="{{Request::is('admin/teams*') ? 'active' : '' }}">
    <a href="{{ route('teams') }}">
        <span class="icon fa fa-users"></span><span class="title">Teams</span>
    </a>
</li>
<li class="{{Request::is('admin/scheludes*') ? 'active' : '' }}">
    <a href="{{ route('scheludes') }}">
        <span class="icon fa fa-users"></span><span class="title">Scheludes</span>
    </a>
</li>

resources/views/admin/photo_preview.blade.php
<img src="{{route('imagecache', ['template' => 'small', 'filename' => $photo->path . $photo->name])}}" class="file-preview-image" title="{{$photo->meta_title}}" alt="{{$photo->meta_alt}}">

resources/views/admin/user.blade.php
@extends('admin.index')

@section('content')
    <div class="side-body">
        <div class="page-title">
            <span class="title">User {{ $user->first_name }} {{ $user->last_name }}</span>
        </div>
        <form action="{{ $user->id ? route('user', ['id' => $user->id]) : route('create-user') }}" method="post">
            <div class="row">
                <div class="col-xs-8">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="card">
                                <div class="card-header">
                                    <div class="card-title">
                                        <div class="title">Info</div>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="sub-title">First name</div>
                                    <div>
                                        <input type="text" class="form-control" name="first_name" placeholder="First name" value="{{ object_get($user, 'first_name', old('first_name')) }}">
                                    </div>
                                    <div class="sub-title">Last name</div>
                                    <div>
                                        <input type="text" class="form-control" name="last_name" placeholder="Last name" value="{{ object_get($user, 'last_name', old('last_name')) }}">
                                    </div>
                                    <div class="sub-title">Surname</div>
                                    <div>
                                        <input type="text" class="form-control" name="surname" placeholder="Surname" value="{{ object_get($user, 'surname', old('surname')) }}">
                                    </div>
                                    <div class="sub-title">Phone</div>
                                    <div>
                                        <input type="text" class="form-control" name="phone" placeholder="Phone" value="{{ object_get($user, 'phone', old('phone')) }}">
                                    </div>
                                    <div class="sub-title">Email</div>
                                    <div>
                                        <input type="email" class="form-control" name="email" placeholder="Email" value="{{ object_get($user, 'email', old('email')) }}">
                                    </div>
                                    <div class="sub-title">Birthday d/m/y</div>
                                    <div class="row">
                                        <div class="col-xs-1">
                                            <select class="form-control" name="day">
                                                @for($i = 1; $i <= 31; $i++)
                                                    <option {{array_get($user->split_birthday, 2) == $i ? 'selected' : '' }} value="{{$i}}">{{$i}}</option>
                                                @endfor
                                            </select>
                                        </div>
                                        <div class="col-xs-1">
                                            <select class="form-control" name="month">
                                                @for($i = 1; $i <= 12; $i++)
                                                    <option {{array_get($user->split_birthday, 1) == $i ? 'selected' : '' }} value="{{$i}}">{{$i}}</option>
                                                @endfor
                                            </select>
                                        </div>
                                        <div class="col-xs-2">
                                            <select class="form-control" name="year">
                                                @for($i = 1950; $i <= 2016; $i++)
                                                    <option {{array_get($user->split_birthday, 0) == $i ? 'selected' : '' }} value="{{$i}}">{{$i}}</option>
                                                @endfor
                                            </select>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                      <div class="sub-title">Roles</div>
                                      <div>
                                          <select class="form-control multiple-select" name="roles[]" multiple="multiple">
                                              @foreach($roles as $role)
                                                  <option {{ object_get($user, 'roles', collect(old('roles', [])))->contains($role->id) ? 'selected' : '' }} value="{{ $role->id }}">{{ $role->name }}</option>
                                              @endforeach
                                          </select>
                                      </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-4">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="card">
                                <div class="card-header">
                                    <div class="card-title">
                                        <div class="title">Save</div>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="btn-group btn-group-justified" role="group" aria-label="...">
                                        <div class="btn-group">
                                            <input type="submit" class="btn btn-success" role="button" value="Save">
                                        </div>
                                        @if(!$user->is('superadmin') && $user->id)
                                            <div class="btn-group">
                                                <a class="btn btn-danger" href="{{ route('delete-user', [$user->id]) }}">Delete</a>
                                            </div>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="card">
                                <div class="card-header">
                                    <div class="card-title">
                                        <div class="title">Password</div>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="sub-title">Password</div>
                                    <div>
                                        <input type="password" class="form-control" name="password" placeholder="Password" value="">
                                    </div>
                                    <div class="sub-title">Password confirmation</div>
                                    <div>
                                        <input type="password" class="form-control" name="password_confirmation" placeholder="Password confirmation" value="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    @if($user->id)
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="card">
                                    <div class="card-header">
                                        <div class="card-title">
                                            <div class="title">Image</div>
                                        </div>
                                    </div>
                                    <div class="card-body">
                                        <script>
                                        var photo = {!! ($user->photo ? json_encode($user->photo->getData()) : '{}') !!};
                                        </script>
                                        <input type="file" name="image" class="image-upload" data-upload-url="{{ route('photo-user-upload', ['user', $user->id]) }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endif
                </div>
            </div>
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
        </form>
    </div>
@endsection